name : Uncover daily run

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-binary:
    runs-on: ubuntu-latest
    environment: github
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make uncover executable
        run: chmod +x .github/bin/uncover

      - name: Debug token presence
        run: |
          if [ -z "${C2_TOKEN}" ]; then
            echo "❌ Token is EMPTY"
            exit 1
          else
            echo "✅ Token is present: ${C2_TOKEN:0:4}****"
          fi
        env:
          C2_TOKEN: ${{ secrets.C2_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Run binary and generate data
        env:
          ONYPHE_API_KEY: ${{ secrets.ONYPHE_API_KEY }}
        run: |
          chmod +x ./generate.sh
          ./generate.sh

      - name: Commit and push data
        env:
          C2_TOKEN: ${{ secrets.C2_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${C2_TOKEN}@github.com/${{ github.repository }}
          git add data/
          git commit -m "Daily data for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
